
complete -c ansifilter -s i -l input -r -d 'Name of input file'
complete -c ansifilter -s o -l output -r -d 'Name of output file'
complete -c ansifilter -s O -l outdir -r -d 'Name of output directory'
complete -c ansifilter -s x -l max-size -r -d 'Set maximum input file size (default: 256M)'
complete -c ansifilter -s t -l tail -d 'Continue reading after end-of-file (like tail -f)'
complete -c ansifilter -s T -l text -d 'Output text'
complete -c ansifilter -s H -l html -d 'Output HTML'
complete -c ansifilter -s M -l pango -d 'Output Pango Markup'
complete -c ansifilter -s L -l latex -d 'Output LaTeX'
complete -c ansifilter -s P -l tex -d 'Output Plain TeX'
complete -c ansifilter -s R -l rtf -d 'Output RTF'
complete -c ansifilter -s S -l svg -d 'Output SVG'
complete -c ansifilter -s B -l bbcode -d 'Output BBCODE'
complete -c ansifilter -s a -l anchors -xa 'self' -d 'Add HTML line anchors (opt: self referencing, assumes -l)'
complete -c ansifilter -s d -l doc-title -r -d 'Set HTML/LaTeX/SVG document title'
complete -c ansifilter -s e -l encoding -r -d 'Set HTML/RTF encoding or omit if NONE'
complete -c ansifilter -s f -l fragment -d 'Omit HTML header and footer'
complete -c ansifilter -s F -l font -r -d 'Set HTML/RTF/SVG font face'
complete -c ansifilter -s k -l ignore-clear -xa '0 1' -d 'Do not adhere to clear (ESC K) commands (default: true'
complete -c ansifilter -s c -l ignore-csi -d 'Do not adhere to CSI commands'
complete -c ansifilter -s l -l line-numbers -d 'Print line numbers in output file'
complete -c ansifilter -s m -l map -r -d 'Read color mapping file'
complete -c ansifilter -s r -l style-ref -r -d 'Set HTML/TeX/LaTeX/SVG stylesheet path'
complete -c ansifilter -s s -l font-size -r -d 'Set HTML/RTF/SVG font size'
complete -c ansifilter -s p -l plain -d 'Ignore ANSI formatting information'
complete -c ansifilter -s w -l wrap -r -d 'Wrap long lines'
complete -c ansifilter -l no-trailing-nl -d 'Omit trailing newline'
complete -c ansifilter -l no-version-info -d 'Omit version info comment'
complete -c ansifilter -l wrap-no-numbers -d 'Omit line numbers of wrapped lines'
complete -c ansifilter -l derived-styles -d 'Output dynamic stylesheets (HTML/SVG)'
complete -c ansifilter -l art-cp437 -d 'Parse codepage 437 ANSI art'
complete -c ansifilter -l art-bin -d 'Parse BIN/XBIN ANSI art'
complete -c ansifilter -l art-tundra -d 'Parse Tundra ANSI art'
complete -c ansifilter -l art-width -r -d 'Set ANSI art width'
complete -c ansifilter -l art-height -r -d 'Set ANSI art height'
complete -c ansifilter -l height -r -d 'set SVG image height'
complete -c ansifilter -l width -r -d 'set SVG image width'
complete -c ansifilter -s v -l version -d 'Print version and license info'
complete -c ansifilter -s h -l help -d 'Print help'
